micronaut:
    application:
        name: DropwizardDashboard
    server:
        port: 8081
    router:
        static-resources:
            default:
                enabled: true
                mapping: /**
                paths: classpath:frontend

endpoints:
    health:
        enabled: true

mongodb:
    uri: mongodb://localhost:27017/dropwizard_dashboard
    dbname: dropwizard_dashboard

